name: Build and Release

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore PolyLauncher.sln

    - name: Build and Publish
      run: dotnet publish PolyLauncher.csproj -c Release -o ./publish

    - name: Create Zip
      shell: pwsh
      run: Compress-Archive -Path ./publish/* -DestinationPath PolyLauncher.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PolyLauncher-Release
        path: PolyLauncher.zip
